# Name of website
title: Modular Synthesis Resource Guide

# Your name to show in the footer
author: Eik

plugins:
  - jekyll-remote-theme

#github approved theme
remote_theme: pages-themes/midnight@v0.2.0

